#!/bin/bash

if [ $# -lt 1 ]; then
  echo "usage: $0 ifile1 ifile2 ... ifilen"
  exit
fi

while [ x"$1" != x ]; do
  IFILE="$1"
  OFILE=`echo $IFILE | sed 's/\.js$/\.min\.js/'`
  java -jar ./compiler/compiler.jar --js $IFILE --js_output_file $OFILE
  shift
done
