#!/bin/bash
#set -x

JS9_SRCDIR=$(pwd)
if [ x"$1" != x ]; then
  case "$1" in
  -q*)
  ./mkhelper nodejs
  ;;

  *)
  JS9_INSTALLDIR="$1"
  ;;
  esac
fi

# js9: message script
IMSGSCR="js9.in"
OMSGSCR="js9"

echo "Generating $OMSGSCR script for JS9 messaging and Desktop use ..."
X="s#^ *JS9_SRCDIR=\".*\"#export JS9_SRCDIR=\"$JS9_SRCDIR\"#"
X="$X;s#^ *JS9_INSTALLDIR=\".*\"#export JS9_INSTALLDIR=\"$JS9_INSTALLDIR\"#"
sed "$X" < $IMSGSCR > $OMSGSCR
chmod +x $OMSGSCR

exit 0
