#!/bin/bash
# set -x

WEBDIR=""
if [ x"$1" != x ]; then
  WEBDIR="$1"
fi

# js9: message script
IMSGSCR="js9.in"
OMSGSCR="js9"

echo "generating $OMSGSCR for js9 messaging ..."
jtype=`egrep '"helperType" *:' js9Prefs.json | awk -F: '{print $NF}' | sed 's/"//g' | sed 's/^[ 	]*//;s/[,} 	]*$//'`
if [ x"$jtype" != x ]; then
    echo "helper type: $jtype"
    X="$X;s#^JTYPE=\".*\"#JTYPE=\"$jtype\"#"
fi
jport=`egrep '"helperPort" *:' js9Prefs.json | awk -F: '{print $2}' | sed 's/"//g' | sed 's/[,} ]*$//' | sed 's/^ *//;s/ *$//'`
if [ x"$jport" != x ]; then
    X="$X;s#^JPORT=\".*\"#JPORT=\"$jport\"#"
fi
X="$X;s#^WEBDIR=\".*\"#WEBDIR=\"$WEBDIR\"#"
sed "$X" < $IMSGSCR > $OMSGSCR
chmod +x $OMSGSCR

exit 0
