#!/bin/sh
# set -x
rm -rf ./config.cache

if [ x"$1" = x ]; then
  name=`uname -n`
else
  if [ x"$1" = x"--" ]; then
    name=`uname -n`
  else
    name="$1"
  fi
  shift
fi

if [ x"$CFLAGS" = x ]; then
  CFLAGS="-g"
  export CFLAGS
fi
if [ x"$LDFLAGS" = x ]; then
  LDFLAGS="-g"
  export LDFLAGS
fi

GCCFLAGS="-W -Wall -Wno-implicit-int -O2"
STRICTFLAGS="-pedantic -Wall -Wpointer-arith -Wcast-align -Wstrict-prototypes -Wredundant-decls -Wnested-externs -Wconversion -Wno-implicit-int"
CF="--config-cache"

echo "configure for: " $name

case $name in
  js9*)
  BASE=/proj/web-js9
  ./configure 	$CF							\
		--with-helper="nodejs"					\
		--prefix=$BASE						\
		--with-webdir=$BASE/www/js9				\
		--with-cfitsio=$BASE					\
		--with-png=$BASE					\
		--with-saodir=$BASE/www					\
		CC=gcc CFLAGS="$CFLAGS $GCCFLAGS" $*
  ;;

  baba|baba.local|baba-nodejs)
  ./configure 	$CF							\
		--with-helper="socket.io"				\
		--prefix=$HOME						\
		--with-webdir=$HOME/Sites/js9				\
		--with-cfitsio=$HOME					\
		--with-png=$HOME					\
		--with-saodir=$HOME/Sites				\
		CC=gcc CFLAGS="$CFLAGS $GCCFLAGS" $*
  ;;

  baba-cgi)
  ./configure 	$CF							\
		--with-helper="post"					\
		--prefix=$HOME						\
		--with-webdir=$HOME/Sites/js9				\
		--with-cfitsio=$HOME					\
		--with-png=$HOME					\
		--with-cgidir=$HOME/Sites/cgi-bin			\
		--with-cgiurl='~'$USER'/cgi-bin'			\
		--with-cgixpath=$HOME/bin				\
		--with-saodir=$HOME/Sites				\
		CC=gcc CFLAGS="$CFLAGS $GCCFLAGS" $*
  ;;

  baba-none)
  ./configure 	$CF --with-webdir=$HOME/Sites/js9			\
		CC=gcc CFLAGS="$CFLAGS $GCCFLAGS" $*
  ;;

 baba-funtools)
  ./configure 	$CF							\
		--with-helper="socket.io"				\
		--prefix=$HOME						\
		--with-webdir=$HOME/Sites/js9				\
		--with-funtools=$HOME					\
		--with-png=$HOME					\
		--with-saodir=$HOME/Sites				\
		CC=gcc CFLAGS="$CFLAGS $GCCFLAGS" $*
  ;;

  bokhara*)
  BASE=/home/mred/public_html
  ./configure 	$CF							\
		--with-helper="post"					\
		--prefix=$HOME						\
		--with-cfitsio=$HOME					\
		--with-webdir=$BASE/htdocs/js9				\
		--with-cgidir=$BASE/cgi-bin/js9				\
		--with-cgiurl=cgi-bin/js9				\
		--with-cgixpath=/soft/saord/bin				\
		CC=gcc CFLAGS="$CFLAGS $GCCFLAGS"			\
		$*
  ;;

  lynx*)
  BASE=/smartx
  ./configure 	$CF							\
		--with-helper="nodejs"					\
		--prefix=$BASE						\
		--with-webdir=$BASE/www/html/js9			\
		--with-cfitsio=$BASE/cfitsio				\
		--with-png=$BASE					\
  		CC=gcc CFLAGS="$CFLAGS $GCCFLAGS"			\
 		$*
  ;;

  smartx*)
  BASE=/smartx
  ./configure 	$CF							\
		--with-helper="nodejs"					\
		--prefix=$BASE						\
		--with-webdir=$BASE/js9/www/js9				\
		--with-cfitsio=$BASE/cfitsio				\
		--with-png=$BASE					\
		CC=gcc CFLAGS="$CFLAGS $GCCFLAGS"			\
		$*
  ;;

  *)
  ./configure 	$CF $*
  ;;

esac
