#!/bin/sh
# set -x
rm -rf ./config.cache

if [ x"$1" = x ]; then
  name=`uname -n`
else
  if [ x"$1" = x"--" ]; then
    name=`uname -n`
  else
    name="$1"
  fi
  shift
fi

if [ x"$CFLAGS" = x ]; then
  CFLAGS="-g"
  export CFLAGS
fi
if [ x"$LDFLAGS" = x ]; then
  LDFLAGS="-g"
  export LDFLAGS
fi

GCCFLAGS="-W -Wall -Wno-implicit-int"
STRICTFLAGS="-pedantic -Wall -Wpointer-arith -Wcast-align -Wstrict-prototypes -Wredundant-decls -Wnested-externs -Wconversion -Wno-implicit-int"
CF="--config-cache"

echo "configure for: " $name

case $name in
  strict)
  ./configure	$CF					\
		CC=gcc CFLAGS="$CFLAGS $STRICTFLAGS" $*
  ;;

  bokhara*)
  ./configure 	$CF							\
		--prefix=/soft/saord					\
		--with-webdir=/home/mred/public_html/htdocs/js9		\
		--with-helper=get					\
		--with-cfitsio=/proj/rd/linux64				\
		--with-png=/proj/rd/linux64				\
		--with-cgidir=/home/mred/public_html/cgi-bin/js9	\
		--with-cgiurl=./cgi-bin/js9				\
		--with-cgixpath=/soft/saord/bin				\
  		CC=gcc CFLAGS="$CFLAGS $GCCFLAGS"			\
 		$*
  ;;

  mred*)
  ./configure 	$CF							\
		--prefix=/export/eric					\
		--with-webdir=/home/mred/public_html/htdocs/js9		\
		--with-helper="nodejs"					\
		--with-cfitsio=/export/eric				\
		--with-png=/export/eric					\
  		CC=gcc CFLAGS="$CFLAGS $GCCFLAGS"			\
 		$*
  ;;

  smartx*)
  ./configure 	$CF							\
		--prefix=/smartx					\
		--with-webdir=/smartx/www/html/js9			\
		--with-helper=nodejs					\
		--with-funtools=/smartx					\
		--with-png=/smartx					\
  		CC=gcc CFLAGS="$CFLAGS $GCCFLAGS"			\
 		$*
  ;;

  baba|baba.local|baba-nodejs)
  ./configure 	$CF							\
		--prefix=$HOME						\
		--with-webdir=$HOME/Sites/js9				\
		--with-helper="socket.io"				\
		--with-cfitsio=/usr/local				\
		--with-png=/usr/local					\
		--with-saodir=$HOME/Sites				\
		CC=gcc CFLAGS="$CFLAGS $GCCFLAGS" $*
  ;;

 baba-funtools)
  ./configure 	$CF							\
		--prefix=$HOME						\
		--with-webdir=$HOME/Sites/js9				\
		--with-helper="socket.io"				\
		--with-funtools=$HOME					\
		--with-png=/usr/local					\
		--with-saodir=$HOME/Sites				\
		CC=gcc CFLAGS="$CFLAGS $GCCFLAGS" $*
  ;;

  baba-cgi)
  ./configure 	$CF							\
		--prefix=$HOME						\
		--with-webdir=$HOME/Sites/js9				\
		--with-helper=get					\
		--with-cfitsio=/usr/local				\
		--with-png=/usr/local					\
		--with-cgidir=$HOME/Sites/cgi-bin			\
		--with-cgiurl=$HOME/cgi-bin				\
		--with-cgixpath=/usr/local/bin				\
		--with-saodir=$HOME/Sites				\
		CC=gcc CFLAGS="$CFLAGS $GCCFLAGS" $*
  ;;

  baba-none)
  ./configure 	$CF --with-webdir=$HOME/Sites/js9			\
		CC=gcc CFLAGS="$CFLAGS $GCCFLAGS" $*
  ;;

  js9*)
  BASE=/proj/web-js9
  ./configure 	$CF							\
		--prefix=$BASE						\
		--with-cfitsio=$BASE					\
		--with-png=$BASE					\
		--with-webdir=$BASE/www/js9				\
		--with-saodir=$BASE/www					\
		--with-helper=nodejs					\
		CC=gcc CFLAGS="$CFLAGS $GCCFLAGS" $*
  ;;

  ascpub*)
  ASCPUB=/proj/web-chandra/htdocs/edu/stop/js9
  ./configure 	$CF							\
		--with-webdir=$ASCPUB					\
		--with-helper=none					\
  		CC=gcc CFLAGS="$CFLAGS $GCCFLAGS"			\
 		$*
  ;;

  *)
  ./configure 	$CF $*
  ;;

esac
